<a href="https://colab.research.google.com/github/yuliethzapata/Analitica-de-Negocios/blob/main/1_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Caso de Estudio**
En este documento se desarolla y analiza un modelo Naive Bayes para la PreaAprobación de créditos en una entidad financiera utilizando las variables socioeconómicas de un solicitante de crédito. De acuerdo con lo anterior las variables socioeconómicas son:
**Edad**: Es la edad que posee el solicitante al momento de solicitar un crédito.
**Ingreso**: Ingresos recibidos por una persona como resultado de una actividad comercial.
**Egresos**: Son los gastos mensuales del solicitante. Gastos de personas a cargos, hijos y servicios públicos.
**Monto (EAD)**:Indica el dinero que una persona solicita a una entidad financiera como crédito.

0. Se procede con la carga de las librerías de trabajo

In [ ]:
import numpy as np #Libreria númerica por excelencia.
import pandas as pd #Libreria para la comunicación con archivos de excel.

#Librerias especificas
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

1. Se cargan los datos de trabajo de la base de datos BaseAAA

In [ ]:
nxl="/content/1. SolicitantesCrédito(USD) (1).xlsx"
XDB=pd.read_excel(nxl,sheet_name=1)
#XDB.head(100) #Es para mostrar la base de datos cargada

#Seleccionamos variables de trabajo
XD=XDB[['Edad','Ingresos','Egresos','Monto (EAD)']] #Variables de trabajo
XD.head(10)
yd=XDB[['PreApr']] #Esta la variable de decisión
yd.head()

,PreApr
0,1
1,1
2,0
3,1
4,1


2. Implementamos Modelo Naive Bayes

In [ ]:
mnb=GaussianNB()
mnb.fit(XD,yd) #Ajustar Variables Entrada - Salida

#Mostramos las medias de las variables
u=mnb.theta_
sigma=mnb.var_;sigma=np.sqrt(sigma)
print('Edad','Ingresos','Egresos','Monto (EAD)')
print(u)
print("Las desviaciones son:")
print(sigma)

Edad Ingresos Egresos Monto (EAD)
[[  40.98411626  431.42680644  401.54995644  289.41445941]
 [  41.10752688 1029.98947251  900.19312144  781.2021157 ]]
Las desviaciones son:
[[ 12.21303268 325.79791497 342.77286087 235.95783541]
 [ 12.25106493 472.43342807 525.43337837 469.90038088]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Análisis de Resultados**
De los resultados arojados por el modelo, podemos observar que la categoria de PreAprobados posee ingresos superiores a las categorias de PreNegados , esto indica claramente la predominancia de la variable para aprobar créditos. Es importante mencionar que la edad es mayor para los PreAprobados que los PreNegados, lo que indica que el banco busca personas con mayor experiencia crediticia. Podemos decir igualmente que los PreAprobados tienen egresos superiores a los de la categoria PreNegados, sin embargo, los PreAprobados estan solicitando montos superiores a los de la categoria de PreNegados, esto es un indicador de la capacidad de este grupo para hacer frente a un crédito.

3. Se procede con la evaluación del modelo. Para la evaluación de este tipo de modelos se utiliza la matriz de confusión.


In [ ]:
ydp=mnb.predict(XD)  #Esto es lo que el modelo aprende - yd de pronóstico
cm=confusion_matrix(yd,ydp)
print(cm)

#Se determinan las metricas de las matriz de confusión
VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1];Tdatos=len(XDB)

#1. Exactitud: Funcionamiento general del modelo
Ex=(VP+VN)/Tdatos
print("Exactitud: ",Ex)

#2. Tasa Error: %Fallos del Modelo
TE=(FP+FN)/Tdatos
print("Tasa Error: ",TE)

#3. Sensibilidad: Como se comportó con respecto a los positivos solamente
Se=VP/(VP+FN)
print("Sensibilidad: ",Se)

#4. Especificidad: Como se comporta pronósticando negativos
Es=VN/(VN+FP)
print("Especificidad: ",Es)

#5. Precisión: Es una versión de como se comporta el modelo frente a los positivos solamente
Pr=VP/(VP+FP)
print("Precisión: ",Pr)

#6. Predicción Negativa: Como funciona el modelo pronósticando créditos PreNegadps
PrN=VN/(VN+FN)
print("Predicción Negativa: ",PrN)


[[2502  457]
 [ 937 1946]]
Exactitud:  0.7613830879835672
Tasa Error:  0.23861691201643273
Sensibilidad:  0.6749913284772806
Especificidad:  0.8455559310577898
Precisión:  0.8098210570120683
Predicción Negativa:  0.7275370747310265


**Análisis de Resultados**
De acuerdo con los resultados podemos observar de manera general que el modelo alcanzó una exactitud por encima del 75% del promedio, lo que indica el buen comportamiento del modelo frente a la clasificación de los solicitantes de crédito frente a la PreAprobación y la PreNegación. Se destaca la Precisión con un 80.9% lo que indica el buen funcionamiento del modelo frente a la PreAprobación de créditos, igualmente se puede observar que el buen comportamiento del modelo frente a la PreNegación de créditos tal y como lo demuestra el indice de especificidad del modelo, el cual estuvo por encima del 84% en promedio. Es importante mencionar que le exactitud queda por debajo del 80% ya que esta métrica se ve afectada por los errores en la clasificación de solicitantes de crédito, lo que se evidencia a traves de la Sencibilidad y la Predicción Negativa.

4. Evaluamos un solicitante

In [ ]:
XP=[34,1500,800,1000]
ydc=mnb.predict([XP])
print(ydc)

if ydc==1:
  print("El solicitante es PreAprobado")
else:
  print("El solicitante es Negado")

[1]
El solicitante es PreAprobado


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
